- name: Disable Default Redis and enable 7 Version
  ansible.builtin.shell: dnf module disable redis -y && dnf module enable redis:7 -y

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: installed

- name: Update Listen Address from 127.0.0.1 to 0.0.0.0 in /etc/redis/redis.conf
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
    backup: yes

- name: Update Redis config file
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'
    backup: yes

- name: Start Redis
  ansible.builtin.dnf:
    name: redis
    state: started

