- name: Mysql setup
  hosts: all
  become: true
  tasks:
    - name: Install MMYSQL Server
      ansible.builtin.shell: dnf install mysql-server -y
    - name: Enable Mysql
      ansible.builtin.shell: systemctl enable mysqld
    - name: Start Mysql
      ansible.builtin.shell: systemctl start mysqld
    - name: Secure Mysql
      ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
