- name: set up payment
  hosts: all
  become: true
  tasks:
    - name: Install Python3
      ansible.builtin.shell: dnf install python3 gcc python3-devel -y
    - name: Add user roboshop
      ansible.builtin.shell: useradd roboshop
    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: download payment content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
        dest: /tmp
    - name: unzip payment content
      ansible.builtin.unzip:
        src: /tmp/payment-v3.zip
        dest: /app
    - name: install requirements
      ansible.builtin.shell: cd /app; pip3 install -r requirements.txt
    - name: copy payment config
      ansible.builtin.copy:
        src: payment.service
        dest: /etc/systemd/system/payment.service
    - name: daemon reload
      ansible.builtin.shell: systemctl daemon-reload
    - name: enable payment
      ansible.builtin.shell: systemctl enable payment
    - name: start payment
      ansible.builtin.shell: systemctl start payment