- name: User setup
  hosts: all
  become: true
  tasks:
    - name: Disable nodejs
      ansible.builtin.shell: dnf module disable nodejs -y
    - name: Enable nodejs:20
      ansible.builtin.shell: dnf module enable nodejs:20 -y
    - name: Install nodejs
      ansible.builtin.shell: dnf install nodejs -y
    - name: Add user roboshop
      ansible.builtin.user: name=roboshop
    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: download user content
      ansible.builtin.shell: curl -o /tmp/user.zip https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
    - name: unzip user content
      ansible.builtin.shell: cd /app; unzip /tmp/user.zip
    - name: install node modules
      ansible.builtin.shell: cd /app; npm install
    - name: copy user config
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service
    - name: daemon reload
      ansible.builtin.shell: systemctl daemon-reload
    - name: enable user
      ansible.builtin.shell: systemctl enable user
    - name: start user
      ansible.builtin.shell: systemctl start user