- name: Install rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Enable rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: enabled

- name: Start rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: started

- name: add user
  ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

- name: set permissions
  ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"

- name: restart rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: restarted
