- name: Install MYSQL server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: enable mysqld
  ansible.builtin.dnf:
    name: mysqld
    state: enabled

- name: start mysqld
  ansible.builtin.dnf:
    name: mysqld
    state: started

- name: secure mysql installation
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1